
version: 2
updates:

  - package-ecosystem: "github-actions"
    # this checks the .github/workflows directory by default
    # any other directory for github-actions seems broken at the moment
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "rin-skylight"

  - package-ecosystem: "terraform"
    directory: "/ops"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "rin-skylight"

  - package-ecosystem: "terraform"
    directory: "/templates"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "rin-skylight"

  - package-ecosystem: "docker"
    directory: "/docs"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "rin-skylight"

  - package-ecosystem: "docker"
    directory: "/containers"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "rin-skylight"