name: Terraform Action Deployment
description: Build and push Docker image to the registry
inputs:
  azure_creds:
    description: Azure credentials
    required: true
  deploy_env:
    description: The environment to deploy to
    required: true
  terraform_arm_client_id:
    description: Terraform ARM client ID
    required: true
  terraform_arm_client_secret:
    description: Terraform ARM client secret
    required: true
  terraform_arm_subscription_id:
    description: Terraform ARM subscription ID
    required: true
  terraform_arm_tenant_id:
    description: Terraform ARM tenant ID
    required: true

runs:
  using: composite
  steps:
    - uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_creds }}
    - uses: hashicorp/setup-terraform@v3.0.0
      with:
        terraform_version: 1.7.4
    - name: Set variables
      working-directory: ./octopus
      shell: bash
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV  
    - name: Terraform Init
      working-directory: ./ops
      env: # all Azure interaction is through Terraform
        ARM_CLIENT_ID: ${{ inputs.terraform_arm_client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.terraform_arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.terraform_arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.terraform_arm_tenant_id }}
        OCTOPUS_VERSION: ${{ env.VERSION }}
      shell: bash
      run: make init-${{ inputs.deploy_env }}
    - name: Terraform Apply
      working-directory: ./ops
      env: # all Azure interaction is through Terraform
        ARM_CLIENT_ID: ${{ inputs.terraform_arm_client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.terraform_arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.terraform_arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.terraform_arm_tenant_id }}
        OCTOPUS_VERSION: ${{ env.VERSION }}
      shell: bash
      run: make deploy-${{ inputs.deploy_env }}
