name: Deploy Dev
run-name: Deploy to ${{ inputs.deploy_env }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - ""
          - dev

concurrency:
  group: ${{ github.event.inputs.deploy_env }}-deploy
  cancel-in-progress: false

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push docs container
        uses: ./.github/actions/build-and-push-docs
        with:
          acr_registry: ${{ secrets.ACR_REPO_URL }}
          acr_username: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
          acr_password: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}

  deploy_infra:
    runs-on: ubuntu-latest
    needs: [build_docs]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-deploy
        name: Deploy with Terraform
        with:
          azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
          deploy_env: ${{ inputs.deploy_env }}
          terraform_arm_client_id: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
          terraform_arm_client_secret: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
          terraform_arm_subscription_id: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
          terraform_arm_tenant_id: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
