name: Deploy Global

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - ""
          - global

env:
  DEPLOY_ENV: global

concurrency:
  group: global-deploy
  cancel-in-progress: false

jobs:
  workflow_changes:
    with:
      what_to_check: ./.github
    uses: ./.github/workflows/checkForChanges.yml

  octopus_changes:
      with:
        what_to_check: ./octopus
      uses: ./.github/workflows/checkForChanges.yml

  build_docs:
    if: needs.workflow_changes.outputs.has_changes == 'true' || needs.octopus_changes.outputs.has_changes == 'true' || github.ref == 'refs/heads/main'
    needs:
      - workflow_changes
      - octopus_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Octopus container
        uses: ./.github/actions/build-and-push-octopus
        with:
          acr_registry: ${{ secrets.ACR_REPO_URL }}
          acr_username: ${{ secrets.ACR_ADMIN_USERNAME }}
          acr_password: ${{ secrets.ACR_ADMIN_PASSWORD }}
  
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-deploy
        name: Deploy with Terraform
        with:
          azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
          deploy_env: ${{ env.DEPLOY_ENV }}
          terraform_arm_client_id: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
          terraform_arm_client_secret: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
          terraform_arm_subscription_id: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
          terraform_arm_tenant_id: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
