name: Build and Push Docs Container
run-name: Build and Push Docs Container by @{{github.actor}}

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read
    packages: write

jobs:
    build_and_push_docker_ghcr:
        runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v4
            - name: Set short git commit SHA
              shell: bash
              id: vars
              run: |
                calculatedSha=$(git rev-parse --short ${{ github.sha }})
                echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

            - name: Confirm git commit SHA output
              shell: bash
              run: |
                echo ${{ vars.env.COMMIT_SHORT_SHA }}   

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./docs
                  file: Dockerfile
                  tags: ghcr.io/cdcgov/dibbs-cloud/docs:${{ vars.env.COMMIT_SHORT_SHA }}
  
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
  
            - name: Push image to Github Container Registry
              run: |
                  docker push ghcr.io/cdcgov/dibbs-cloud/docs:${{ vars.env.COMMIT_SHORT_SHA }}