name: Ad-hoc Terraform Plan

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment target"
        required: true
        default: "prod" 

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ops
    env: # all Azure interaction is through Terraform
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TERRAFORM_ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.7.3
      - name: Terraform Init
        run: make init-${{ github.event.inputs.env }}
      - name: Terraform plan
        run: make plan-${{ github.event.inputs.env }}